### ISSUE TITLE
problem in reproduce MMMU benchmark

### ISSUE THREAD

**Issue by lyklly** [Liuziyu77/MIA-DPO#2]
![1731649158081](https://github.com/user-attachments/assets/83e4e6c1-eb1f-4fce-95cf-3054d4c1062c)
notice that llava 1.5 7b can reach 35.1% in MMMU in paper. However, i find the file "llava1.5_13b_val.json" official have provided can reach this  accuracy, but llava 1.5 7b can only reach  25.4% .
is there any problem here or did i make a mistake?

**Comment by Liuziyu77** [comment]
what's this file “llava1.5_13b_val.json”？

**Comment by lyklly** [comment]
here, https://github.com/MMMU-Benchmark/MMMU/blob/main/mmmu/example_outputs/llava1.5_13b_val.json

**Comment by lyklly** [comment]
but i can't get the accuracy showed in the paper whether I evaluate it myself or just use VlmEvalKit

**Comment by Liuziyu77** [comment]
Do you mean that when testing the LLaVa7B baseline, you were unable to reproduce the result of 35.1?

**Comment by Liuziyu77** [comment]
Maybe you can refer to the Leaderboard of VLMEvalKit：https://huggingface.co/spaces/opencompass/open_vlm_leaderboard
